### ISSUE TITLE
[Bug] App crashes after first use

### ISSUE THREAD

**Issue by collectorgeneral** [bottiger/SoundWaves#77]
I installed the app yesterday from F-Droid. I start things up, subscribe to a couple of channels. After that, I do something else and try to start the app back, it just crashes everytime. I even tried force closing the app, to no avail. The only way I could get it to work was to force close, and then clear all app data. Then it starts up but the same process just repeats. 

Phone info: 
One Plus One aka Bacon aka A0001 running Android 6.0.1 (Cyanogen OS 13.1)

If you need additional info, let me know.

**Comment by bottiger** [comment]
@collectorgeneral Thank you for getting back to me. Since F-Droid does not allow apps to collect data without user consent I do not get enough feedback from F-droid users.

Here is what you should do. First go into "Settings -> Advanced" and enable "Send anonymous reports". 

Then, when you encounter a crash go into "Settings -> Advanced -> Submit debug log". Submit a report and post the link here. Then I will take a look at it.

This should help me locate and fix your issues, because at the moment I have no idea what the problem could be.

**Comment by bottiger** [comment]
@collectorgeneral I just talked to the team at F-Droid. It can take a few days before the app is updated due to some server problems.

You can always try to install the version on Google Play and see if you can reproduce the problem.

**Comment by collectorgeneral** [comment]
Hmm, it is understandable, an average user might not know how to find repos and report stuff. 

Anyway, here is the log you are looking for:

https://gist.github.com/anonymous/db7389d6e81ee9e2c52bc8230a1be34e

Hope this helps to find your bug.

**Comment by bottiger** [comment]
@collectorgeneral Thank you a lot.  You are correct that it is not obvious at all for F-Droid users to submit a crash log, and it should be improved at some point. However, the two versions are almost identical, so most problems will be identified by users of the Google Play version which submits crashes automatically.

In any case. I just inspected the log and I am sorry to tell you that this is another issue which is fixed in the most recent version. Unfortunately I pushed out a buggy version of the app some time ago, and while I fixed the issue within hours of pushing that F-droid happened to first build and publish the faulty version, and then their build system broke down :(

Again, this should be fixed when they get their servers up and running again.

**Comment by collectorgeneral** [comment]
@bottiger 
Oh, thats unfortunate. Its fine though, as long as the bug is fixed!

**Comment by bottiger** [comment]
@collectorgeneral I will let this bug stay open until the new version is available on F-Droid. Please let me know if the problem really is fixed when it's available.

**Comment by collectorgeneral** [comment]
@bottiger 
Couldn't reproduce the crash so far. So I assume it should be good! BTW check out the other bug I reported, it is still persistant and quite annoying actually.
